//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHomeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetRegistration
    {
        public int AssetId { get; set; }
        public string AssetName { get; set; }
        public System.DateTime RegisteredDate { get; set; }
        public string Address { get; set; }
        public int LandTaxAmount { get; set; }
        public int NumberofDoors { get; set; }
        public int NumberofWindows { get; set; }
        public int NumberofTaps { get; set; }
        public int NumberofFans { get; set; }
        public int NumberofBulbs { get; set; }
        public int IsSump { get; set; }
        public string Remarks { get; set; }
    }
}
