//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHomeDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyHomeDBEntities : DbContext
    {
        public MyHomeDBEntities()
            : base("name=MyHomeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AssetRegistration> AssetRegistrations { get; set; }
        public virtual DbSet<EmergencyContact> EmergencyContacts { get; set; }
        public virtual DbSet<MailLog> MailLogs { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<PropertyTax> PropertyTaxes { get; set; }
        public virtual DbSet<Proximity> Proximities { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<TenentAgreement> TenentAgreements { get; set; }
        public virtual DbSet<TenentRequest> TenentRequests { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    }
}
