//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHomeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyTax
    {
        public int PropertyID { get; set; }
        public int AssetName { get; set; }
        public System.DateTime TaxDate { get; set; }
        public int TaxAmount { get; set; }
        public int Status { get; set; }
        public string Remarks { get; set; }
    }
}
