//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHomeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proximity
    {
        public int ProximityId { get; set; }
        public string AssetName { get; set; }
        public string RailwayStation { get; set; }
        public string BusStation { get; set; }
        public string Airport { get; set; }
        public string MetroStation { get; set; }
        public string SchoolorCollege { get; set; }
        public string Hospital { get; set; }
        public string Market { get; set; }
        public string Temple { get; set; }
        public string Hotel { get; set; }
    }
}
