//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHomeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenentRequest
    {
        public int TenentRequestId { get; set; }
        public int AssetName { get; set; }
        public string Description { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Response { get; set; }
        public int Status { get; set; }
    }
}
