//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHomeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenentAgreement
    {
        public int AgreementId { get; set; }
        public int AssetName { get; set; }
        public int ResidentsNumber { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public System.DateTime LeavingDate { get; set; }
        public string ResidentsNames { get; set; }
        public string IdentityProofs { get; set; }
        public int AdvanceAmount { get; set; }
        public int RentAmount { get; set; }
        public int PercentageIncreased { get; set; }
        public string ContactNumbers { get; set; }
        public string TenentEmailId { get; set; }
        public string Remarks { get; set; }
        public int RentDueDate { get; set; }
    }
}
